name: Publish dev docker images
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  docker-publish:
    name: Docker publish
    runs-on: ubuntu-latest
    if: github.repository_owner == 'discordjs'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the image
        run: docker build -t discordjs/proxy:latest -f packages/proxy-container/Dockerfile .

      - name: Push image to DockerHub
        run: docker push discordjs/proxy:latest
